apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-attacher-role-cfg
  namespace: dlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-attacher-cfg
subjects:
- kind: ServiceAccount
  name: csi-attacher
  namespace: dlf
