apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-attacher-role-nfs
  namespace: dlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-attacher-runner-nfs
subjects:
- kind: ServiceAccount
  name: csi-attacher-nfs
  namespace: dlf
