apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-nodeplugin-h3
  namespace: dlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-nodeplugin-h3
subjects:
- kind: ServiceAccount
  name: csi-nodeplugin-h3
  namespace: dlf
