apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-provisioner-role-cfg
  namespace: dlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-provisioner-cfg
subjects:
- kind: ServiceAccount
  name: csi-provisioner
  namespace: dlf
