apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi-provisioner-s3
  name: csi-provisioner-s3
  namespace: dlf
spec:
  ports:
  - name: dummy
    port: 12345
  selector:
    app: csi-provisioner-s3
