apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataset-operator
  namespace: dlf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dataset-operator
subjects:
- kind: ServiceAccount
  name: dataset-operator
  namespace: dlf
