apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-attacher-cfg
  namespace: dlf
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
